services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admocorrencia
      MINIO_ROOT_PASSWORD: bebaagua!
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
  database:
    image: "postgres:16"
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=admocorrencia"
      - "POSTGRES_DB=ocorrenciaapi"
      - "POSTGRES_PASSWORD=bebaagua!"
