CREATE TABLE usuario
(
    cod_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login       VARCHAR(100)                            NOT NULL,
    senha       VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (cod_usuario)
);